[program:sdr-native]
priority=30
command=/usr/local/bin/start-native.sh
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/sdr/native.stdout.log
stderr_logfile=/var/log/sdr/native.stderr.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[program:sdr-backend]
priority=40
command=/usr/local/bin/start-backend.sh
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/sdr/backend.stdout.log
stderr_logfile=/var/log/sdr/backend.stderr.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[program:sdr-ui]
priority=50
command=/usr/local/bin/start-ui.sh
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/sdr/ui.stdout.log
stderr_logfile=/var/log/sdr/ui.stderr.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
